[build]
functions = "netlify/functions"
publish = "public"

[[redirects]]
# Redirect all API requests to the serverless function
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
# Redirect all undefined routes to index.html for SPA handling
from = "/*"
to = "/index.html"
status = 200
