[build]
functions = "netlify/functions"
publish = "public"

[[redirects]]
# Redirects API routes to the serverless function
from = "/auth/*"
to = "/.netlify/functions/api/auth/:splat"
status = 200

from = "/dashboard/*"
to = "/.netlify/functions/api/dashboard/:splat"
status = 200

from = "/matches/*"
to = "/.netlify/functions/api/matches/:splat"
status = 200

from = "/admin/*"
to = "/.netlify/functions/api/admin/:splat"
status = 200

from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

# Redirect all undefined routes to the root index.html (SPA handling)
from = "/*"
to = "/index.html"
status = 200
